/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cage_NativeCaGePipe */

#ifndef _Included_cage_NativeCaGePipe
#define _Included_cage_NativeCaGePipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cage_NativeCaGePipe
 * Method:    initCaGePipe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cage_NativeCaGePipe_initCaGePipe
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    startCaGePipe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cage_NativeCaGePipe_startCaGePipe
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    finalizeCaGePipe
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cage_NativeCaGePipe_finalizeCaGePipe
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    setAdvanceTarget
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cage_NativeCaGePipe_setAdvanceTarget
  (JNIEnv *, jobject, jint);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    getAdvanceTarget
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cage_NativeCaGePipe_getAdvanceTarget
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    nStartAdvancing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cage_NativeCaGePipe_nStartAdvancing
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    getGraph
 * Signature: ()Lcage/EmbeddableGraph;
 */
JNIEXPORT jobject JNICALL Java_cage_NativeCaGePipe_getGraph
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    wouldBlock
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cage_NativeCaGePipe_wouldBlock
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeCaGePipe
 * Method:    setGraphNoFireInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cage_NativeCaGePipe_setGraphNoFireInterval
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
