/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cage_NativeEdgeIterator */

#ifndef _Included_cage_NativeEdgeIterator
#define _Included_cage_NativeEdgeIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cage_NativeEdgeIterator
 * Method:    nHasNextEdge
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_cage_NativeEdgeIterator_nHasNextEdge
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEdgeIterator
 * Method:    nGetNextEdge
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cage_NativeEdgeIterator_nGetNextEdge
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEdgeIterator
 * Method:    nFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEdgeIterator_nFinalize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
