/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cage_writer_NativePlanarWriter */

#ifndef _Included_cage_writer_NativePlanarWriter
#define _Included_cage_writer_NativePlanarWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cage_writer_NativePlanarWriter
 * Method:    nEncodeGraph
 * Signature: (Lcage/NativeEmbeddableGraph;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cage_writer_NativePlanarWriter_nEncodeGraph
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cage_writer_NativePlanarWriter
 * Method:    header
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cage_writer_NativePlanarWriter_header
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
