/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cage_writer_NativeCMLWriter */

#ifndef _Included_cage_writer_NativeCMLWriter
#define _Included_cage_writer_NativeCMLWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cage_writer_NativeCMLWriter
 * Method:    nEncodeGraph
 * Signature: (Lcage/NativeEmbeddableGraph;Lcage/ElementRule;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cage_writer_NativeCMLWriter_nEncodeGraph
  (JNIEnv *, jobject, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
