/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cage_writer_NativeWritegraphWriter */

#ifndef _Included_cage_writer_NativeWritegraphWriter
#define _Included_cage_writer_NativeWritegraphWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cage_writer_NativeWritegraphWriter
 * Method:    nEncodeGraph
 * Signature: (Lcage/NativeEmbeddableGraph;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cage_writer_NativeWritegraphWriter_nEncodeGraph
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     cage_writer_NativeWritegraphWriter
 * Method:    header
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_cage_writer_NativeWritegraphWriter_header
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
