/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cage_NativeEmbeddableGraph */

#ifndef _Included_cage_NativeEmbeddableGraph
#define _Included_cage_NativeEmbeddableGraph
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    newNGraph
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_cage_NativeEmbeddableGraph_newNGraph
  (JNIEnv *, jobject);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGetComment
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cage_NativeEmbeddableGraph_nGetComment
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nSetComment
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbeddableGraph_nSetComment
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGetFormat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cage_NativeEmbeddableGraph_nGetFormat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nSetFormat
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbeddableGraph_nSetFormat
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nAddVertex
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbeddableGraph_nAddVertex
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nAddEdge
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbeddableGraph_nAddEdge
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_cage_NativeEmbeddableGraph_nGetSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGetValency
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_cage_NativeEmbeddableGraph_nGetValency
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGetEdgeIterator
 * Signature: (JI)Lcage/NativeEdgeIterator;
 */
JNIEXPORT jobject JNICALL Java_cage_NativeEmbeddableGraph_nGetEdgeIterator
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nHas2DCoordinates
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_cage_NativeEmbeddableGraph_nHas2DCoordinates
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGet2DCoordinates
 * Signature: (JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cage_NativeEmbeddableGraph_nGet2DCoordinates
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGetAll2DCoordinates
 * Signature: (J)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_cage_NativeEmbeddableGraph_nGetAll2DCoordinates
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nSet2DCoordinates
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbeddableGraph_nSet2DCoordinates
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nHas3DCoordinates
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_cage_NativeEmbeddableGraph_nHas3DCoordinates
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGet3DCoordinates
 * Signature: (JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cage_NativeEmbeddableGraph_nGet3DCoordinates
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nGetAll3DCoordinates
 * Signature: (J)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_cage_NativeEmbeddableGraph_nGetAll3DCoordinates
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nSet3DCoordinates
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbeddableGraph_nSet3DCoordinates
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    toBytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_cage_NativeEmbeddableGraph_toBytes
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbeddableGraph
 * Method:    nFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbeddableGraph_nFinalize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
