/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cage_NativeEmbedEmbedder */

#ifndef _Included_cage_NativeEmbedEmbedder
#define _Included_cage_NativeEmbedEmbedder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cage_NativeEmbedEmbedder
 * Method:    nCompileCommands
 * Signature: ([Ljava/lang/Object;[B[B)J
 */
JNIEXPORT jlong JNICALL Java_cage_NativeEmbedEmbedder_nCompileCommands
  (JNIEnv *, jobject, jobjectArray, jbyteArray, jbyteArray);

/*
 * Class:     cage_NativeEmbedEmbedder
 * Method:    nEmbed2D
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbedEmbedder_nEmbed2D
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     cage_NativeEmbedEmbedder
 * Method:    nEmbed3D
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbedEmbedder_nEmbed3D
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     cage_NativeEmbedEmbedder
 * Method:    nFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbedEmbedder_nFinalize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     cage_NativeEmbedEmbedder
 * Method:    nStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_cage_NativeEmbedEmbedder_nStop
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
