/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lisken_systoolbox_Systoolbox */

#ifndef _Included_lisken_systoolbox_Systoolbox
#define _Included_lisken_systoolbox_Systoolbox
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lisken_systoolbox_Systoolbox
 * Method:    nGetEnv
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_lisken_systoolbox_Systoolbox_nGetEnv
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
